<a href="https://colab.research.google.com/github/mengcius/pytorch-learn/blob/master/2_%E5%88%9B%E5%BB%BATensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 2.PyTorch创建Tensor

### 从numpy导入

In [0]:
import torch
import numpy as np

In [0]:
a=np.array([2,3.3])
torch.from_numpy(a) #转为torch的类型

tensor([2.0000, 3.3000], dtype=torch.float64)

In [0]:
a=np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [0]:
a=np.array([2,3.3])
a

array([2. , 3.3])

### 从List导入

直接写数据，数据少时可以用

In [0]:
torch.tensor([2.,3.3]) #tensor接受数据，建议使用这种方法

tensor([2.0000, 3.3000])

In [0]:
torch.FloatTensor(2,3) #FloatTensor接受维度，建议使用这种方法

tensor([[5.6178e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

下面的方法不建议使用，易混淆

In [0]:
torch.FloatTensor([2.,3.3]) #FloatTensor也能接受数据

tensor([2.0000, 3.3000])

In [0]:
torch.Tensor([2.,3.3]) #Tensor接受数据，有[ ]

tensor([2.0000, 3.3000])

In [0]:
torch.Tensor(2,3) #Tensor接受维度，没有[ ]，2行3列

tensor([[5.6177e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

### 设置默认类型

.tensor和.Tensor默认代表.FloatTensor类型。

增强学习一般使用double，精度更高，其他一般使用float

In [0]:
torch.tensor([1.2,3]).type()

'torch.FloatTensor'

In [0]:
torch.set_default_tensor_type(torch.DoubleTensor) #设置默认类型
torch.tensor([1.2,3]).type()

'torch.DoubleTensor'

### 生成未初始化的数据
有时希望申请的内存空间不需要提前初始化，只做个容器，注意未初始化的tensor后面一定要跟着写入数据的后续步骤。未初始化就给神经网络的，会报错（nan inf等）。有3种方法：

torch.empty()

torch.FloatTensor(d1, d2, d3)

torch.IntTensor(d1, d2, d3)

In [0]:
torch.empty(1) #数据是随机无规则的，极大、极小或0

tensor([5.6184e-36])

In [0]:
torch.Tensor(2,3)

tensor([[5.6187e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [0]:
torch.FloatTensor(2,3)

tensor([[5.6187e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [0]:
torch.IntTensor(2,3)

tensor([[82771648,        0,       32],
        [       0,       -1,        0]], dtype=torch.int32)

### 随机初始化
普通无规则的初始化可能会有一些问题，推荐使用随机初始化。

rand：随机的使用0-1间均匀分布的数值，不包括1


In [0]:
torch.rand(3,3) #接受shape参数

tensor([[0.3180, 0.5997, 0.5236],
        [0.6629, 0.9012, 0.6812],
        [0.2276, 0.9720, 0.6694]])

*_like，模仿给的tensor的shape

In [0]:
a=torch.rand(3,3)
torch.rand_like(a) #rand_like直接接受一个tensor(使用的了它的shape)

tensor([[0.4213, 0.1917, 0.2355],
        [0.8828, 0.3387, 0.3266],
        [0.9887, 0.2965, 0.7633]])

In [0]:
torch.randint(1,10,[3,3]) #randint采样整数项，3个参数：min max shape

tensor([[8, 4, 7],
        [6, 7, 7],
        [8, 6, 6]])

### 正态分布
randn，最常用的是均值为0，方差为1的正态分布

In [0]:
torch.randn(3,3) #默认均值为0，方差为1

tensor([[ 0.0914,  0.2476,  0.1246],
        [-1.2668,  0.2263, -0.9290],
        [ 0.2216,  0.6743,  0.2789]])

自定义均值和方差

In [0]:
#full生成10个0；arange方差是从1到0不断减少，即[1,0.9,...,0.1]，不包含右边界0。
torch.normal(mean=torch.full([10],0),std=torch.arange(1,0,-0.1))

tensor([-0.7571, -0.4181, -0.4790,  1.4926,  0.2363,  0.3513, -0.1105, -0.2969,
         0.1454, -0.0479])

### 全部赋一个值

In [0]:
torch.full([2,3],7) #全赋为7

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [0]:
torch.full([],7) #0维，标量

tensor(7.)

In [0]:
torch.full([1],7) #1维

tensor([7.])

### 等差数列

In [0]:
torch.arange(0,10) #递增的等差数列，默认差为1，左必右开[0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
torch.arange(0,10,2) #设置差为2 

tensor([0, 2, 4, 6, 8])

In [0]:
torch.range(0,10) #torch中不建议使用range

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 等分切割

linspace，等分切割

In [0]:
torch.linspace(0,10,steps=4) #将[0,10]等分切割成4份

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [0]:
torch.linspace(0,10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [0]:
torch.linspace(0,10,steps=11) #11份正好

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

logspace，等分切割后取对数，它的base参数可以设置为2,10,e等参数

In [0]:
torch.logspace(0,1,steps=10) #等分10份，默认以10为底，

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

### 生成全部是1/0/eye

In [0]:
torch.ones(2,3) #生成全部是1，参数给shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:
torch.zeros(2,3) #生成全部是1，参数给shape

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [0]:
torch.eye(2,3) #生成全部是1，参数给shape，shape不是对角矩阵的话多余部分默认填0

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [0]:
torch.eye(3) #参数给一个，生成对角矩阵

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
a=torch.zeros(3,3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

numpy中表示

In [0]:
np.zeros((2,3))
np.ones((2,3),int)
np.empty((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

### 随机打散
random.shuffle，希望两个可以协同打散，两者打乱时也保持配对


In [0]:
torch.randperm(10) #随机打散10个数

tensor([8, 3, 4, 1, 7, 5, 2, 6, 9, 0])

In [0]:
a=torch.rand(2,3) #a和b配对，打乱时都只将第一维同时打乱
b=torch.rand(2,2)
a,b

(tensor([[0.4668, 0.4583, 0.0470],
         [0.7515, 0.9098, 0.5587]]), tensor([[0.1719, 0.8072],
         [0.8556, 0.4060]]))

In [0]:
idx=torch.randperm(2) #随机打散2个数，它俩当作随机种子，用来当作a的随机索引
idx

tensor([1, 0])

In [0]:
a[idx] #a和b用同一个种子，同一个类别的一起匹配变化

tensor([[0.7515, 0.9098, 0.5587],
        [0.4668, 0.4583, 0.0470]])

In [0]:
b[idx]

tensor([[0.8556, 0.4060],
        [0.1719, 0.8072]])

In [0]:
a,b

(tensor([[0.4668, 0.4583, 0.0470],
         [0.7515, 0.9098, 0.5587]]), tensor([[0.1719, 0.8072],
         [0.8556, 0.4060]]))