<a href="https://colab.research.google.com/github/mengcius/pytorch-learn/blob/master/3_%E7%B4%A2%E5%BC%95%E4%B8%8E%E5%88%87%E7%89%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.索引与切片

### 直接索引

直接给定索引 [ ]

In [0]:
import torch
import numpy as np

In [0]:
a=torch.rand(4,3,28,28) # batch,c,h,w
a[0] #从最左边开始索引，第一个维度，这里指第0张图片
a[0].shape

torch.Size([3, 28, 28])

In [0]:
a[0,0].shape #第0张图片的第0个通道

torch.Size([28, 28])

In [0]:
a[0,0,2,4] #第0张图片的第0个通道的第2行第4列像素，注意这里返回的是0维的标量，不同于[0.8918]

tensor(0.8918)

### 切片，选取前面或后面连续的一部分
连续取前面一部分用 :+数字 可以理解为->，只有 : 表示取全部，取后面用 数字+: 。

In [0]:
a=torch.rand(4,3,28,28) # batch,c,h,w
a.shape

torch.Size([4, 3, 28, 28])

In [0]:
a[:2].shape #第1维度的取前2个，第0、1个，没有取到第2个，相当于:右面是开区间

torch.Size([2, 3, 28, 28])

In [0]:
a[:2,:,27:,-2:].shape #-1代表最后一个，:左面是闭区间，第27、-2(26)个（0-27）

torch.Size([2, 3, 1, 2])

In [0]:
a[:2,:,27:,-2:]

tensor([[[[0.7316, 0.7230]],

         [[0.5899, 0.6945]],

         [[0.6761, 0.1977]]],


        [[[0.0406, 0.4303]],

         [[0.8266, 0.2562]],

         [[0.3794, 0.4430]]]])

### 间隔采样
[start:end) 从开始到结束，左闭右开

[start:end:step)有间隔时有两个 : ，0:28:2，2就是间隔，不写时默认为1




In [0]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [0]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

### 指定维度索引

index_select，第一个参数是第几维，第二个参数选取此维度上元素的索引范围，要将list转为tersor

In [0]:
a.index_select(0,torch.tensor([0,2])).shape #选第几个维度，对此维度取第0、2

torch.Size([2, 3, 28, 28])

In [0]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [0]:
a.index_select(2,torch.arange(8)).shape #arange是0-7等差数列

torch.Size([4, 3, 8, 28])

### 任意维度
... 指所有维度

In [0]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [0]:
a[0,...].shape

torch.Size([3, 28, 28])

In [0]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [0]:
a[...,:3].shape #取第3维度的前3个

torch.Size([4, 3, 28, 3])

### mask掩码索引

缺点是数据会默认打平，打平是因为大于0.5的元素个数是根据内容才能确定的

In [0]:
x=torch.randn(3,4)
x

tensor([[-0.7588,  0.0759,  0.6084,  1.6877],
        [-1.3070,  1.1828, -1.0166,  0.4488],
        [ 0.8180,  0.2789,  1.3226, -2.7183]])

In [0]:
mask=x.ge(0.5) #ge：大于等于0.5的元素置为1，把这个矩阵作为mask
mask

tensor([[0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 0]], dtype=torch.uint8)

In [0]:
torch.masked_select(x,mask) #打平为[1,12]，在里面取出与mask中1的位置对应的元素

tensor([0.6084, 1.6877, 1.1828, 0.8180, 1.3226])

In [0]:
torch.masked_select(x,mask).shape

torch.Size([5])

### 选择打平的索引



In [0]:
src=torch.tensor([[4,3,5],[6,7,8]])
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [0]:
torch.take(src,torch.tensor([0,2,5])) #选择打平[2,3]->[1,6]后的索引

tensor([4, 5, 8])