<a href="https://colab.research.google.com/github/mengcius/pytorch-learn/blob/master/6_%E6%95%B0%E5%AD%A6%E8%BF%90%E7%AE%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 6.数学运算

add/minus/multiply/divide 加减乘除

matmul 矩阵相乘

pow/sqrt 次方与平方根

exp/log 以e为底的指数和对数

round 近似运算

clamp 裁剪值的范围

### add/sub/mul/div 加减乘除
推荐直接使用重载的运算符号：+ - * / （// 整除）

对应的代码为.add/sub/mul/div()，英文对应为Add/minus/multiply/divide



In [0]:
import torch

In [0]:
a=torch.zeros(3,4)
b=torch.ones(4)
a+b #加，会先默认把维度对齐，把b变为[3,4]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
torch.add(a,b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
torch.all(torch.eq(a-b,torch.sub(a,b))) #减

tensor(1, dtype=torch.uint8)

In [0]:
torch.all(torch.eq(a*b,torch.mul(a,b))) #乘，按相同位置的元素相乘

tensor(1, dtype=torch.uint8)

In [0]:
torch.all(torch.eq(a/b,torch.div(a,b))) #减

tensor(1, dtype=torch.uint8)

### matmul 矩阵相乘
@ 符号形式，矩阵乘，符合行列式规则

torch.matmul                                          
torch.mm 只能适用于2维，不常用

In [0]:
a=torch.zeros(3,4)
b=torch.ones(4)

In [0]:
a@b #矩阵乘，符合行列式规则

tensor([0., 0., 0.])

In [0]:
torch.matmul(a,b)

tensor([0., 0., 0.])

In [0]:
a=torch.zeros(3,4)
b=torch.ones(4,3)
torch.mm(a,b) #只能二维

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

网络层中矩阵相乘的举例

In [0]:
x=torch.rand(4,784)
w=torch.rand(512,784) #它负责将x降维到512，torch默认第一参数是ch-out，第二参数是ch-in

In [0]:
(x@w.t()).shape #相乘时要将w转置，t()只适用于2维 

torch.Size([4, 512])

多维矩阵相乘，matmul只将最后两个维度相乘，其他维度不一样时可自动扩展

In [0]:
a=torch.rand(4,3,28,64)
b=torch.rand(4,3,64,32)
# torch.mm(a,b).shape #不能用于多维
torch.matmul(a,b).shape #多维矩阵相乘，只将最后两个维度相乘

torch.Size([4, 3, 28, 32])

In [0]:
a=torch.rand(4,3,28,64)
b=torch.rand(4,1,64,32) #相乘时1会被自动扩展为3
torch.matmul(a,b).shape #多维矩阵相乘，只将最后两个维度相乘

torch.Size([4, 3, 28, 32])

In [0]:
a=torch.rand(4,3,28,64)
b=torch.rand(3,64,32) #自动扩展
torch.matmul(a,b).shape #多维矩阵相乘，只将最后两个维度相乘

torch.Size([4, 3, 28, 32])

In [0]:
a=torch.zeros(3,3,4)
b=torch.ones(1,4,3)
(a@b).shape 

torch.Size([3, 3, 3])

In [0]:
a=torch.rand(4,3,28,64)
b=torch.rand(4,64,32) #无法自动扩展，只能是空/1/相等
torch.matmul(a,b).shape #多维矩阵相乘，只将最后两个维度相乘

RuntimeError: ignored

### pow/sqrt 次方与平方根
pow 次方，power

sqrt 平方根，square root


In [0]:
a=torch.full([2,3],3)
a.pow(2) #2次方

tensor([[9., 9., 9.],
        [9., 9., 9.]])

In [0]:
a**2 #2次方

tensor([[9., 9., 9.],
        [9., 9., 9.]])

In [0]:
aa=a**2
aa.sqrt() #平方根

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [0]:
aa.rsqrt() #平方根的倒数

tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

In [0]:
aa**(0.5) #0.5表示1/2，开平方

tensor([[3., 3., 3.],
        [3., 3., 3.]])

### exp/log 以e为底的指数和对数

In [0]:
torch.exp(torch.tensor(1.)) #e的几次方，e=2.7183

tensor(2.7183)

In [0]:
a=torch.exp(torch.ones(2,2)) 
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [0]:
torch.log(a) #取以e为底的Log

tensor([[1., 1.],
        [1., 1.]])

In [0]:
torch.log10(a) #取以10为底的Log

tensor([[0.4343, 0.4343],
        [0.4343, 0.4343]])

### 取近似值
.floor() .ceil()

.trunc() .frac()

.round()


In [0]:
a=torch.tensor(3.14)
a.floor(), a.ceil() #向下取整，向上取整

(tensor(3.), tensor(4.))

In [0]:
a.trunc(), a.frac() #取整数，取小数

(tensor(3.), tensor(0.1400))

In [0]:
a.round() #四舍五入

tensor(3.)

### clamp 裁剪值的范围
可用于梯度裁剪，可解决梯度离散（消失）和梯度离散。

w.grad 打印梯度

w.grad.norm(2) 打印梯度的模，L2范数（值一般在10左右）

In [0]:
grad=torch.rand(2,3)*15
grad

tensor([[ 8.2453, 14.0579,  1.7637],
        [ 6.2943, 11.9355,  0.0870]])

In [0]:
grad.max()

tensor(14.0579)

In [0]:
grad.median()

tensor(6.2943)

In [0]:
grad.clamp(10) #(min)，使它的最小值为10，即小于10的都变为10

tensor([[10.0000, 14.0579, 10.0000],
        [10.0000, 11.9355, 10.0000]])

In [0]:
grad.clamp(8,10) #(min,max)，使范围在8-10之间

tensor([[ 8.2453, 10.0000,  8.0000],
        [ 8.0000, 10.0000,  8.0000]])